{
 "title": "MT-MMMS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Input",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total OCR Words per document",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "ocr_word_count{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}OCR Word Count"
      }
     ]
    },
    {
     "title": "Total OCR Words Distribution",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "ocr_word_count{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}OCR Word Count"
      }
     ]
    },
    {
     "title": "Total Question Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "question_word_length{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Question length"
      }
     ]
    },
    {
     "title": "Question length Distribution",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "question_word_length{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Question Length"
      }
     ]
    },
    {
     "title": "Average Bounding Box Area over time",
     "type": "timeseries",
     "description": "Average Bounding Box Area in pixel over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "avg_bounding_box_area{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Average Bounding Box Area"
      }
     ]
    },
    {
     "title": "Distribution of Average Bounding Box Area",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "avg_bounding_box_area{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Image Dimensions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pixel" } },
     "targets": [
      {
       "expr": "image_height_pixels{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Image Height"
      },
      {
       "expr": "image_width_pixels{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Image Width"
      }
     ]
    },
    {
     "title": "Image Dimensions",
     "type": "histogram",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "pixel" } },
     "targets": [
      {
       "expr": "image_height_pixels{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Image Height"
      },
      {
       "expr": "image_width_pixels{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{label_name}}Image Width"
      }
     ]
    },
    {
     "title": "Relative Bounding Box Coverage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "bounding_box_coverage{model_name=\"layoutlmv3\", job=\"flask_app\"}",
       "legendFormat": "{{model_name}}"
      }
     ]
    },
    {
     "title": "Top 100 Token IDs",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "topk(100, rate(token_usage_total{model_name=\"layoutlmv3\", token_id!=\"1\"}[1m]))\r\n",
       "legendFormat": "{{token_id}}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Mean Initialization Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "initialization_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{part}}"
    }
   ]
  },
  {
   "title": "Total Amount of successful Inferences",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "successful_inferences_total{model_name=\"layoutlmv3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Amount of unsuccessful Inferences",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unsuccessful_inferences{model_name=\"layoutlmv3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Inferences Throughput per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(successful_inferences_total{model_name=\"layoutlmv3\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per endpoint",
   "type": "timeseries",
   "description": "Latency for each endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "request_latency{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Distribution of Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "request_latency{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Encoding Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "encoding_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Encoding Duration"
    }
   ]
  },
  {
   "title": "Distribution of Encoding Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "encoding_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Encoding Duration"
    }
   ]
  },
  {
   "title": "Backend Inference Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_inference_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Backend Inference Duration"
    }
   ]
  },
  {
   "title": "Distribution of Backend Inference Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "backend_inference_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Backend Inference Duration"
    }
   ]
  },
  {
   "title": "Total Inference Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "total_inference_duration{model_name=\"layoulmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Total Inference Duration"
    }
   ]
  },
  {
   "title": "Total Inference Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "total_inference_duration{model_name=\"layoulmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Total Inference Duration"
    }
   ]
  },
  {
   "title": "Inference Process Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "total_inference_duration{model_name=\"layoulmv3\"}",
     "legendFormat": "{{label_name}}Total Inference Duration"
    },
    {
     "expr": "backend_inference_duration{model_name=\"layoutlmv3\"}",
     "legendFormat": "{{label_name}}Backend Inference Duration"
    },
    {
     "expr": "encoding_duration{model_name=\"layoutlmv3\"}",
     "legendFormat": "{{label_name}}Encoding Duration"
    },
    {
     "expr": "inference_duration",
     "legendFormat": "{{label_name}}Model Inference Duration"
    }
   ]
  },
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Model Inference Duration",
   "type": "timeseries",
   "description": "Total duration for model inference",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inference_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Model Inference Duration"
    }
   ]
  },
  {
   "title": "Distribution of Model Inference Duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "inference_duration{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Model Inference Duration"
    }
   ]
  },
  {
   "title": "Confidence Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confidence_score{job=\"flask_app\", model_name=\"layoutlmv3\"}",
     "legendFormat": "{{score_type}}"
    }
   ]
  },
  {
   "title": "Confidence Score Difference",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confidence_score_difference{model_name=\"layoutlmv3\", job=\"flask_app\"}",
     "legendFormat": "{{label_name}}Confidence Score Difference"
    }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "User Feedback Rate of past 1 Minutes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(user_feedback_counter_total{model_name=\"layoutlmv3\"}[1m])",
     "legendFormat": "{{feedback_type}}"
    }
   ]
  },
  {
   "title": "Count of failed Inferences",
   "type": "stat",
   "description": "Total amount of failed inferences by model with empty string as result",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "failed_inference_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Feedback Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_feedback_counter_total{model_name=\"layoutlmv3\"}",
     "legendFormat": "{{feedback_type}}"
    }
   ]
  }
 ]
}