scrape_configs:
  - job_name: 'flask_app'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx_exporter:9113']


  # - job_name: docker
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["host.docker.internal:9323"]